import type { Metadata } from "next";
import "./globals.css";

import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";
import { Navbar } from "@/components/Navbar";
import { getMe } from "@/service/getme";
import { Suspense } from "react";
import GlobalLoading from "./loading";


export const metadata: Metadata = {
  title: "RentNest",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getMe();

  return (
    <html lang="en" className={cn("h-full", "antialiased")}>
      <body className="min-h-screen flex flex-col">
     
        <Navbar user={user} />

       
        <main className="flex-grow">
          <Suspense fallback={<GlobalLoading />}>
            {children}
          </Suspense>
        </main>

   
        <Footer />

      
        <Toaster position="top-right" richColors />
      </body>
    </html>
  );
}
