import type { Metadata } from "next";

import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import { cn } from "@/lib/utils";
import { Toaster } from "sonner";




export const metadata: Metadata = {
  title: "RentNest",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased")}
    >
      <body className="min-h-screen flex flex-col">
    <Navbar></Navbar>
     
        <main className="flex-grow">{children}
        <Toaster position = "top-right" richColors></Toaster>

        </main>
        <Footer></Footer>
        </body>
    </html>
  );
}
